#!/usr/bin/env python3
"""Scan a project reference PDF library and write index/status files."""

from __future__ import annotations

import argparse
import hashlib
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


@dataclass(frozen=True)
class PdfRecord:
    paper_id: str
    rel_path: str
    size_bytes: int
    sha256: str
    updated: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", default=".", help="Project control root.")
    parser.add_argument("--reference-dir", default="reference", help="Reference directory path.")
    parser.add_argument("--hash-bytes", type=int, default=0, help="Hash only the first N bytes; 0 hashes full files.")
    return parser.parse_args()


def slugify(text: str) -> str:
    stem = re.sub(r"\.[Pp][Dd][Ff]$", "", text)
    stem = re.sub(r"[^A-Za-z0-9]+", "-", stem.lower()).strip("-")
    return stem[:80] or "paper"


def sha256_file(path: Path, limit: int = 0) -> str:
    digest = hashlib.sha256()
    remaining = limit
    with path.open("rb") as handle:
        while True:
            read_size = 1024 * 1024
            if limit and remaining <= 0:
                break
            if limit:
                read_size = min(read_size, remaining)
            chunk = handle.read(read_size)
            if not chunk:
                break
            digest.update(chunk)
            if limit:
                remaining -= len(chunk)
    return digest.hexdigest()


def human_size(size: int) -> str:
    value = float(size)
    for unit in ("B", "K", "M", "G"):
        if value < 1024 or unit == "G":
            if unit == "B":
                return f"{int(value)}B"
            return f"{value:.1f}{unit}"
        value /= 1024
    return f"{value:.1f}G"


def find_pdf_root(reference_dir: Path) -> Path:
    papers_dir = reference_dir / "papers"
    if papers_dir.exists():
        return papers_dir
    return reference_dir


def scan(project_root: Path, reference_dir: Path, hash_bytes: int) -> list[PdfRecord]:
    pdf_root = find_pdf_root(reference_dir)
    records: list[PdfRecord] = []
    used_ids: dict[str, int] = {}
    for path in sorted(pdf_root.rglob("*.pdf")):
        if ".agent" in path.parts:
            continue
        rel = path.relative_to(project_root).as_posix()
        base_id = slugify(path.name)
        count = used_ids.get(base_id, 0)
        used_ids[base_id] = count + 1
        paper_id = base_id if count == 0 else f"{base_id}-{count + 1}"
        stat = path.stat()
        records.append(
            PdfRecord(
                paper_id=paper_id,
                rel_path=rel,
                size_bytes=stat.st_size,
                sha256=sha256_file(path, hash_bytes),
                updated=datetime.fromtimestamp(stat.st_mtime, timezone.utc).date().isoformat(),
            )
        )
    return records


def write_index(reference_dir: Path, records: list[PdfRecord]) -> None:
    agent_dir = reference_dir / ".agent"
    agent_dir.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).date().isoformat()
    lines = [
        "# Reference Index",
        "",
        "Generated by `reference-library-manager`. Keep paths project-relative.",
        "",
        "| Paper ID | File | Size | SHA256 | Metadata status | Roles | Reading state | Card | Project use | Updated |",
        "|---|---|---:|---|---|---|---|---|---|---|",
    ]
    for record in records:
        short_hash = record.sha256[:12]
        card = f"reference/cards/{record.paper_id}.md"
        project_use = f"reference/project-use/{record.paper_id}.md"
        lines.append(
            f"| `{record.paper_id}` | `{record.rel_path}` | {human_size(record.size_bytes)} | `{short_hash}` | missing |  | unread | `{card}` | `{project_use}` | {record.updated} |"
        )
    lines.extend(["", f"- Last scan: {today}", f"- PDF count: {len(records)}", ""])
    (agent_dir / "reference-index.md").write_text("\n".join(lines), encoding="utf-8")


def write_status(reference_dir: Path, records: list[PdfRecord]) -> None:
    agent_dir = reference_dir / ".agent"
    today = datetime.now(timezone.utc).date().isoformat()
    lines = [
        "# Reference Reading Status",
        "",
        "| Paper ID | Priority | Roles | Reading mode | State | Owner | Next action | Updated |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for record in records:
        lines.append(f"| `{record.paper_id}` | skim |  | skim | unread | agent | create card if relevant | {today} |")
    lines.append("")
    (agent_dir / "reading-status.md").write_text("\n".join(lines), encoding="utf-8")


def write_gaps(reference_dir: Path, records: list[PdfRecord]) -> None:
    agent_dir = reference_dir / ".agent"
    lines = ["# Metadata Gaps", "", "| Paper ID | Missing fields | Suggested action |", "|---|---|---|"]
    for record in records:
        lines.append(f"| `{record.paper_id}` | title, authors, year, venue | verify metadata during reading |")
    lines.append("")
    (agent_dir / "metadata-gaps.md").write_text("\n".join(lines), encoding="utf-8")


def write_duplicates(reference_dir: Path, records: list[PdfRecord]) -> None:
    agent_dir = reference_dir / ".agent"
    by_hash: dict[str, list[PdfRecord]] = {}
    for record in records:
        by_hash.setdefault(record.sha256, []).append(record)
    lines = ["# Duplicate Check", "", "| SHA256 | Files |", "|---|---|"]
    duplicates = 0
    for digest, items in sorted(by_hash.items()):
        if len(items) < 2:
            continue
        duplicates += 1
        files = "<br>".join(f"`{item.rel_path}`" for item in items)
        lines.append(f"| `{digest[:12]}` | {files} |")
    if duplicates == 0:
        lines.append("| none | No exact duplicate PDFs found. |")
    lines.append("")
    (agent_dir / "duplicate-check.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    project_root = Path(args.project_root).expanduser().resolve()
    reference_dir = Path(args.reference_dir)
    if not reference_dir.is_absolute():
        reference_dir = project_root / reference_dir
    reference_dir.mkdir(parents=True, exist_ok=True)
    (reference_dir / "cards").mkdir(exist_ok=True)
    (reference_dir / "project-use").mkdir(exist_ok=True)
    (reference_dir / "summaries").mkdir(exist_ok=True)
    (reference_dir / "notes").mkdir(exist_ok=True)
    (reference_dir / ".agent" / "runs").mkdir(parents=True, exist_ok=True)

    records = scan(project_root, reference_dir, args.hash_bytes)
    write_index(reference_dir, records)
    write_status(reference_dir, records)
    write_gaps(reference_dir, records)
    write_duplicates(reference_dir, records)
    print(f"Scanned {len(records)} PDF(s) under {reference_dir}")
    print(f"Wrote {reference_dir / '.agent' / 'reference-index.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
